use anyhow::Result;
use chrono::Utc;
use rust_query::{Select, aggregate, optional};

use crate::schema;
use crate::types::{AddTask, EditTask, Task, TaskId, TaskStatus};
use crate::Db;

/// Internal struct for selecting all task columns from the database.
/// Used by both `get_task` (task.rs) and `list_tasks`/`search` (query.rs).
#[derive(Select)]
pub(crate) struct TaskSelect {
    pub(crate) external_id: i64,
    pub(crate) title: String,
    pub(crate) description: String,
    pub(crate) status: String,
    pub(crate) priority: Option<i64>,
    pub(crate) workspace: String,
    pub(crate) deadline: Option<String>,
    pub(crate) snooze_until: Option<String>,
    pub(crate) planned_date: Option<String>,
    pub(crate) deleted_at: Option<String>,
    pub(crate) created_at: String,
    pub(crate) updated_at: String,
}

impl TaskSelect {
    /// Query helper: fetch all tasks from the database.
    /// This lives here because TaskSelectSelect (generated by derive) is private to this module.
    pub(crate) fn query_all(db: &crate::Db) -> Vec<TaskSelect> {
        db.database.transaction(|txn| {
            txn.query(|q| {
                let t = q.join(schema::Task);
                q.into_vec(TaskSelectSelect {
                    external_id: &t.external_id,
                    title: &t.title,
                    description: &t.description,
                    status: &t.status,
                    priority: &t.priority,
                    workspace: &t.workspace,
                    deadline: &t.deadline,
                    snooze_until: &t.snooze_until,
                    planned_date: &t.planned_date,
                    deleted_at: &t.deleted_at,
                    created_at: &t.created_at,
                    updated_at: &t.updated_at,
                })
            })
        })
    }

    pub(crate) fn into_task(self) -> Result<Task> {
        let status: TaskStatus = self.status.parse()?;
        Ok(Task {
            id: self.external_id,
            title: self.title,
            description: self.description,
            status,
            priority: self.priority,
            workspace: self.workspace,
            deadline: self.deadline,
            snooze_until: self.snooze_until,
            planned_date: self.planned_date,
            deleted_at: self.deleted_at,
            created_at: self.created_at,
            updated_at: self.updated_at,
            github_pr_context: None,
            linear_context: None,
        })
    }
}

fn validate_date(field_name: &str, value: &str) -> Result<()> {
    chrono::NaiveDate::parse_from_str(value, "%Y-%m-%d")
        .map_err(|_| anyhow::anyhow!("{field_name} must be a valid date (YYYY-MM-DD), got: {value}"))?;
    Ok(())
}

impl Db {
    pub fn add_task(&self, params: AddTask) -> Result<TaskId> {
        if let Some(d) = &params.deadline {
            validate_date("deadline", d)?;
        }
        if let Some(d) = &params.planned_date {
            validate_date("planned_date", d)?;
        }

        let now = Utc::now().to_rfc3339();
        let status = params.status.unwrap_or(TaskStatus::Idea).to_string();
        let description = params.description.unwrap_or_default();

        self.database.transaction_mut(|txn| {
            // Generate next external_id: max(external_id) + 1, or 1 if empty
            let next_id: i64 = txn
                .query_one(aggregate(|rows| {
                    let task = rows.join(schema::Task);
                    rows.max(&task.external_id)
                }))
                .map_or(1, |max| max + 1);

            txn.insert(schema::Task {
                external_id: next_id,
                title: params.title.clone(),
                description: description.clone(),
                status: status.clone(),
                priority: params.priority,
                workspace: params.workspace.clone(),
                deadline: params.deadline.clone(),
                snooze_until: None,
                planned_date: params.planned_date.clone(),
                deleted_at: None,
                created_at: now.clone(),
                updated_at: now.clone(),
            })
            .map_err(|_| anyhow::anyhow!("task with this external_id already exists"))?;

            Ok(next_id)
        })
    }

    pub fn edit_task(&self, id: TaskId, params: EditTask) -> Result<()> {
        if let Some(Some(d)) = &params.deadline {
            validate_date("deadline", d)?;
        }
        if let Some(Some(d)) = &params.planned_date {
            validate_date("planned_date", d)?;
        }

        let now = Utc::now().to_rfc3339();

        self.database.transaction_mut(|txn| {
            let task_row = txn
                .query_one(optional(|row| {
                    let task = row.and(schema::Task.external_id(id));
                    row.then(task)
                }))
                .ok_or_else(|| anyhow::anyhow!("task not found: {id}"))?;

            let mut task = txn.mutable(&task_row);

            if let Some(t) = &params.title {
                task.title = t.clone();
            }
            if let Some(d) = &params.description {
                task.description = d.clone();
            }
            if let Some(s) = &params.status {
                task.status = s.to_string();
            }
            if let Some(p) = params.priority {
                task.priority = p;
            }
            if let Some(w) = &params.workspace {
                task.workspace = w.clone();
            }
            if let Some(d) = &params.deadline {
                task.deadline = d.clone();
            }
            if let Some(s) = &params.snooze_until {
                task.snooze_until = s.clone();
            }
            if let Some(p) = &params.planned_date {
                task.planned_date = p.clone();
            }
            task.updated_at = now.clone();

            Ok(())
        })
    }

    pub fn delete_task(&self, id: TaskId) -> Result<()> {
        let now = Utc::now().to_rfc3339();

        self.database.transaction_mut(|txn| {
            let task_row = txn
                .query_one(optional(|row| {
                    let task = row.and(schema::Task.external_id(id));
                    row.then(task)
                }))
                .ok_or_else(|| anyhow::anyhow!("task not found: {id}"))?;

            let mut task = txn.mutable(&task_row);
            task.deleted_at = Some(now.clone());
            task.updated_at = now.clone();

            Ok(())
        })
    }

    pub fn snooze(&self, id: TaskId, until: chrono::NaiveDate) -> Result<()> {
        let now = Utc::now().to_rfc3339();
        let until_str = until.to_string();

        self.database.transaction_mut(|txn| {
            let task_row = txn
                .query_one(optional(|row| {
                    let task = row.and(schema::Task.external_id(id));
                    row.then(task)
                }))
                .ok_or_else(|| anyhow::anyhow!("task not found: {id}"))?;

            let mut task = txn.mutable(&task_row);
            task.snooze_until = Some(until_str.clone());
            task.updated_at = now.clone();

            Ok(())
        })
    }

    pub fn get_task(&self, id: TaskId) -> Result<Option<Task>> {
        let result: Option<TaskSelect> = self.database.transaction(|txn| {
            txn.query_one(optional(|row| {
                let t = row.and(schema::Task.external_id(id));
                row.then_select(TaskSelectSelect {
                    external_id: &t.external_id,
                    title: &t.title,
                    description: &t.description,
                    status: &t.status,
                    priority: &t.priority,
                    workspace: &t.workspace,
                    deadline: &t.deadline,
                    snooze_until: &t.snooze_until,
                    planned_date: &t.planned_date,
                    deleted_at: &t.deleted_at,
                    created_at: &t.created_at,
                    updated_at: &t.updated_at,
                })
            }))
        });

        match result {
            None => Ok(None),
            Some(ts) => {
                let mut task = ts.into_task()?;
                task.github_pr_context = self.load_github_context(task.id)?;
                task.linear_context = self.load_linear_context(task.id)?;
                Ok(Some(task))
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::AddTask;

    fn make_add_task(title: &str, workspace: &str) -> AddTask {
        AddTask {
            title: title.into(),
            description: None,
            status: None,
            priority: None,
            workspace: workspace.into(),
            deadline: None,
            planned_date: None,
        }
    }

    #[test]
    fn test_invalid_dates_rejected() {
        let db = Db::open_in_memory().unwrap();

        let invalid_dates = ["next tuesday", "not-a-date", "2026/03/24", "24-03-2026", ""];

        for bad in &invalid_dates {
            let err = db.add_task(AddTask {
                title: "Test".into(),
                description: None,
                status: None,
                priority: None,
                workspace: "work".into(),
                deadline: Some(bad.to_string()),
                planned_date: None,
            });
            assert!(err.is_err(), "deadline '{bad}' should be rejected");

            let err = db.add_task(AddTask {
                title: "Test".into(),
                description: None,
                status: None,
                priority: None,
                workspace: "work".into(),
                deadline: None,
                planned_date: Some(bad.to_string()),
            });
            assert!(err.is_err(), "planned_date '{bad}' should be rejected");
        }

        // Valid date should succeed
        let id = db.add_task(AddTask {
            title: "Valid date task".into(),
            description: None,
            status: None,
            priority: None,
            workspace: "work".into(),
            deadline: Some("2026-03-24".into()),
            planned_date: Some("2026-04-01".into()),
        });
        assert!(id.is_ok(), "valid dates should be accepted");

        // edit_task: invalid dates rejected
        let task_id = db.add_task(make_add_task("Edit me", "work")).unwrap();
        let err = db.edit_task(
            task_id,
            EditTask {
                deadline: Some(Some("next tuesday".into())),
                ..Default::default()
            },
        );
        assert!(err.is_err(), "edit_task with invalid deadline should be rejected");

        let err = db.edit_task(
            task_id,
            EditTask {
                planned_date: Some(Some("not-a-date".into())),
                ..Default::default()
            },
        );
        assert!(err.is_err(), "edit_task with invalid planned_date should be rejected");

        // Clearing (Some(None)) should still work
        db.edit_task(
            task_id,
            EditTask {
                deadline: Some(None),
                planned_date: Some(None),
                ..Default::default()
            },
        )
        .unwrap();
    }

    #[test]
    fn test_task_crud() {
        let mut db = Db::open_in_memory().unwrap();

        // --- test_add_task ---
        let id = db.add_task(make_add_task("Buy groceries", "personal")).unwrap();
        assert_eq!(id, 1);

        let task = db.get_task(id).unwrap().expect("task should exist");
        assert_eq!(task.title, "Buy groceries");
        assert_eq!(task.status, TaskStatus::Idea);
        assert_eq!(task.workspace, "personal");
        assert_eq!(task.description, "");
        assert!(task.priority.is_none());
        assert!(task.deadline.is_none());
        assert!(task.snooze_until.is_none());
        assert!(task.planned_date.is_none());
        assert!(task.deleted_at.is_none());

        // --- test_add_multiple_tasks ---
        let id2 = db.add_task(make_add_task("Task 2", "work")).unwrap();
        let id3 = db.add_task(make_add_task("Task 3", "personal")).unwrap();
        assert_eq!(id2, 2);
        assert_eq!(id3, 3);

        // --- test_edit_task ---
        let edit_id = db.add_task(make_add_task("Edit me", "personal")).unwrap();

        db.edit_task(
            edit_id,
            EditTask {
                title: Some("Edited title".into()),
                status: Some(TaskStatus::Ready),
                priority: Some(Some(1)),
                ..Default::default()
            },
        )
        .unwrap();

        let task = db.get_task(edit_id).unwrap().expect("task should exist");
        assert_eq!(task.title, "Edited title");
        assert_eq!(task.status, TaskStatus::Ready);
        assert_eq!(task.priority, Some(1));
        assert_eq!(task.workspace, "personal"); // unchanged
        assert_eq!(task.description, ""); // unchanged

        // --- test_delete_task ---
        let del_id = db.add_task(make_add_task("Delete me", "personal")).unwrap();

        db.delete_task(del_id).unwrap();

        let task = db.get_task(del_id).unwrap().expect("task should still exist in db");
        assert!(task.deleted_at.is_some());

        // --- test_snooze_task ---
        let snooze_id = db.add_task(make_add_task("Snoozeable", "personal")).unwrap();

        let until = chrono::NaiveDate::from_ymd_opt(2026, 4, 1).unwrap();
        db.snooze(snooze_id, until).unwrap();

        let task = db.get_task(snooze_id).unwrap().expect("task should exist");
        assert_eq!(task.snooze_until, Some("2026-04-01".to_string()));

        // =====================================================================
        // Query tests (list_tasks + search)
        // =====================================================================
        // Current DB state (non-deleted):
        //   1: "Buy groceries",  personal, Idea,  pri=None, deadline=None, snooze=None, planned=None
        //   2: "Task 2",         work,     Idea,  pri=None, deadline=None, snooze=None, planned=None
        //   3: "Task 3",         personal, Idea,  pri=None, deadline=None, snooze=None, planned=None
        //   4: "Edited title",   personal, Ready, pri=1,    deadline=None, snooze=None, planned=None
        //   5: DELETED
        //   6: "Snoozeable",     personal, Idea,  pri=None, deadline=None, snooze=2026-04-01, planned=None
        //
        // Add more tasks to exercise sorting and filtering:

        use crate::types::TaskFilter;

        // Task with priority 0 (critical) and early deadline
        let id7 = db.add_task(AddTask {
            title: "Critical bug".into(),
            description: Some("Fix the critical production bug".into()),
            status: Some(TaskStatus::InProgress),
            priority: Some(0),
            workspace: "work".into(),
            deadline: Some("2026-03-25".into()),
            planned_date: Some("2026-03-24".into()),
        }).unwrap();
        assert_eq!(id7, 7);

        // Task with priority 2 and later deadline
        let id8 = db.add_task(AddTask {
            title: "Write tests".into(),
            description: Some("Add unit tests for query module".into()),
            status: Some(TaskStatus::Ready),
            priority: Some(2),
            workspace: "work".into(),
            deadline: Some("2026-04-01".into()),
            planned_date: None,
        }).unwrap();
        assert_eq!(id8, 8);

        // Task with priority 1 and no deadline (should sort after pri=1 with deadline)
        let id9 = db.add_task(AddTask {
            title: "Refactor code".into(),
            description: None,
            status: Some(TaskStatus::Ready),
            priority: Some(1),
            workspace: "personal".into(),
            deadline: None,
            planned_date: Some("2026-03-30".into()),
        }).unwrap();
        assert_eq!(id9, 9);

        // Done task
        let id10 = db.add_task(AddTask {
            title: "Old done task".into(),
            description: None,
            status: Some(TaskStatus::Done),
            priority: None,
            workspace: "work".into(),
            deadline: None,
            planned_date: None,
        }).unwrap();
        assert_eq!(id10, 10);

        // --- test: list_tasks excludes deleted tasks ---
        {
            let all = db.list_tasks(TaskFilter::default()).unwrap();
            assert!(all.iter().all(|t| t.deleted_at.is_none()), "deleted tasks should be excluded");
            assert!(!all.iter().any(|t| t.id == 5), "task 5 was deleted");
        }

        // --- test: list_tasks filters by status ---
        {
            let ready_tasks = db.list_tasks(TaskFilter {
                status: Some(TaskStatus::Ready),
                ..Default::default()
            }).unwrap();
            assert!(ready_tasks.iter().all(|t| t.status == TaskStatus::Ready));
            // IDs 4, 8, 9 are Ready
            let ids: Vec<_> = ready_tasks.iter().map(|t| t.id).collect();
            assert!(ids.contains(&4));
            assert!(ids.contains(&8));
            assert!(ids.contains(&9));
        }

        // --- test: list_tasks filters by workspace ---
        {
            let work_tasks = db.list_tasks(TaskFilter {
                workspace: Some("work".into()),
                ..Default::default()
            }).unwrap();
            assert!(work_tasks.iter().all(|t| t.workspace == "work"));
            let ids: Vec<_> = work_tasks.iter().map(|t| t.id).collect();
            assert!(ids.contains(&2));
            assert!(ids.contains(&7));
            assert!(ids.contains(&8));
            assert!(ids.contains(&10));
        }

        // --- test: list_tasks sorts by priority then deadline ---
        {
            // Get all non-snoozed tasks (include_snoozed=false is default)
            // Snoozed task 6 is excluded by default since snooze_until > today
            let tasks = db.list_tasks(TaskFilter {
                include_snoozed: true,
                ..Default::default()
            }).unwrap();

            // Expected priority ordering: 0 first, then 1s, then 2s, then None
            // Within same priority, earlier deadlines first, None-deadline last
            // Verify ordering: all Some(p) before None, and within Some ascending
            let mut prev_pri: Option<i64> = Some(i64::MIN);
            let mut seen_none = false;
            for t in &tasks {
                match t.priority {
                    Some(p) => {
                        assert!(!seen_none, "task with priority appeared after None-priority task");
                        assert!(p >= prev_pri.unwrap_or(i64::MIN), "priorities should be ascending");
                        prev_pri = Some(p);
                    }
                    None => {
                        seen_none = true;
                    }
                }
            }

            // Check the first task is priority 0
            assert_eq!(tasks[0].priority, Some(0));
            assert_eq!(tasks[0].title, "Critical bug");
        }

        // --- test: list_tasks filters snoozed tasks ---
        {
            // Default: snoozed tasks excluded
            let without_snoozed = db.list_tasks(TaskFilter::default()).unwrap();
            assert!(!without_snoozed.iter().any(|t| t.id == 6), "snoozed task should be excluded by default");

            // With include_snoozed: snoozed tasks included
            let with_snoozed = db.list_tasks(TaskFilter {
                include_snoozed: true,
                ..Default::default()
            }).unwrap();
            assert!(with_snoozed.iter().any(|t| t.id == 6), "snoozed task should be included when flag set");
        }

        // --- test: list_tasks filters by has_planned_date ---
        {
            let with_planned = db.list_tasks(TaskFilter {
                has_planned_date: Some(true),
                ..Default::default()
            }).unwrap();
            assert!(with_planned.iter().all(|t| t.planned_date.is_some()));
            let ids: Vec<_> = with_planned.iter().map(|t| t.id).collect();
            assert!(ids.contains(&7)); // "Critical bug" has planned_date
            assert!(ids.contains(&9)); // "Refactor code" has planned_date

            let without_planned = db.list_tasks(TaskFilter {
                has_planned_date: Some(false),
                ..Default::default()
            }).unwrap();
            assert!(without_planned.iter().all(|t| t.planned_date.is_none()));
            assert!(!without_planned.iter().any(|t| t.id == 7));
        }

        // --- test: search matches title substring ---
        {
            let results = db.search("critical", TaskFilter::default()).unwrap();
            assert_eq!(results.len(), 1);
            assert_eq!(results[0].title, "Critical bug");
        }

        // --- test: search matches description substring ---
        {
            let results = db.search("unit tests", TaskFilter::default()).unwrap();
            assert_eq!(results.len(), 1);
            assert_eq!(results[0].title, "Write tests");
        }

        // --- test: search respects workspace filter ---
        {
            // "task" appears in titles across workspaces
            let results = db.search("task", TaskFilter {
                workspace: Some("work".into()),
                ..Default::default()
            }).unwrap();
            assert!(results.iter().all(|t| t.workspace == "work"));
            // "Task 2" is in work, "Task 3" is in personal
            let ids: Vec<_> = results.iter().map(|t| t.id).collect();
            assert!(ids.contains(&2));
            assert!(!ids.contains(&3));
        }

        // --- test: add_attachment ---
        {
            use crate::types::NewAttachment;

            let att_id = db.add_attachment(
                id, // task 1: "Buy groceries"
                NewAttachment {
                    file_name: "receipt.png".into(),
                    content_type: "image/png".into(),
                    data: vec![0x89, 0x50, 0x4e, 0x47],
                    caption: Some("Store receipt".into()),
                },
            ).unwrap();
            assert_eq!(att_id, 1);

            // Second attachment gets id 2
            let att_id2 = db.add_attachment(
                id,
                NewAttachment {
                    file_name: "note.txt".into(),
                    content_type: "text/plain".into(),
                    data: b"hello".to_vec(),
                    caption: None,
                },
            ).unwrap();
            assert_eq!(att_id2, 2);

            // Adding attachment to a non-existent task should error
            let err = db.add_attachment(
                9999,
                NewAttachment {
                    file_name: "x.txt".into(),
                    content_type: "text/plain".into(),
                    data: vec![],
                    caption: None,
                },
            );
            assert!(err.is_err());
        }

        // =====================================================================
        // External context tests (GitHub PR + Linear)
        // =====================================================================

        // --- test_link_github_pr ---
        {
            let pr_task_id = db.add_task(make_add_task("PR task", "work")).unwrap();
            db.link_github_pr(pr_task_id, "https://github.com/rust-lang/rust/pull/42").unwrap();

            let task = db.get_task(pr_task_id).unwrap().expect("task should exist");
            let ctx = task.github_pr_context.expect("should have github context");
            assert_eq!(ctx.repo, "rust-lang/rust");
            assert_eq!(ctx.number, 42);
            assert_eq!(ctx.url, "https://github.com/rust-lang/rust/pull/42");
            assert_eq!(ctx.state, "unknown");
        }

        // --- test_link_github_pr invalid URL ---
        {
            let task_id = db.add_task(make_add_task("Bad PR", "work")).unwrap();
            assert!(db.link_github_pr(task_id, "https://example.com/not-a-pr").is_err());
        }

        // --- test_link_github_pr non-existent task ---
        {
            assert!(db.link_github_pr(9999, "https://github.com/owner/repo/pull/1").is_err());
        }

        // --- test_link_linear ---
        {
            let linear_task_id = db.add_task(make_add_task("Linear task", "work")).unwrap();
            db.link_linear(linear_task_id, "https://linear.app/myteam/issue/ENG-123/some-title").unwrap();

            let task = db.get_task(linear_task_id).unwrap().expect("task should exist");
            let ctx = task.linear_context.expect("should have linear context");
            assert_eq!(ctx.identifier, "ENG-123");
            assert_eq!(ctx.url, "https://linear.app/myteam/issue/ENG-123/some-title");
            assert_eq!(ctx.data, serde_json::json!({}));
        }

        // --- test_link_linear invalid URL ---
        {
            let task_id = db.add_task(make_add_task("Bad Linear", "work")).unwrap();
            assert!(db.link_linear(task_id, "https://example.com/not-linear").is_err());
        }

        // --- test_link_linear non-existent task ---
        {
            assert!(db.link_linear(9999, "https://linear.app/team/issue/ENG-1/title").is_err());
        }

        // --- test: contexts appear in list_tasks ---
        {
            let tasks = db.list_tasks(TaskFilter {
                workspace: Some("work".into()),
                ..Default::default()
            }).unwrap();

            // Find the PR task and Linear task in results
            let pr_task = tasks.iter().find(|t| t.title == "PR task");
            assert!(pr_task.is_some(), "PR task should appear in list");
            assert!(pr_task.unwrap().github_pr_context.is_some(), "PR task should have github context in list");

            let linear_task = tasks.iter().find(|t| t.title == "Linear task");
            assert!(linear_task.is_some(), "Linear task should appear in list");
            assert!(linear_task.unwrap().linear_context.is_some(), "Linear task should have linear context in list");
        }

        // --- test_github_refresh_on_stale ---
        // Swap in a mock HTTP client and config to test refresh behavior.
        {
            use std::sync::Arc;
            use std::time::Duration;
            use crate::http::{HttpClient, IntegrationConfig};

            struct MockHttpClient;

            impl HttpClient for MockHttpClient {
                fn get(&self, _url: &str, _headers: &[(&str, &str)]) -> anyhow::Result<Vec<u8>> {
                    let response = serde_json::json!({
                        "state": "closed",
                        "merged": true,
                        "title": "My PR"
                    });
                    Ok(serde_json::to_vec(&response).unwrap())
                }

                fn post(&self, _url: &str, _headers: &[(&str, &str)], _body: &[u8]) -> anyhow::Result<Vec<u8>> {
                    Err(anyhow::anyhow!("not used"))
                }
            }

            // Create a fresh task for the refresh test
            let refresh_task_id = db.add_task(make_add_task("Refresh test", "work")).unwrap();
            db.link_github_pr(refresh_task_id, "https://github.com/owner/repo/pull/99").unwrap();

            // Verify initial state is "unknown"
            let task = db.get_task(refresh_task_id).unwrap().unwrap();
            assert_eq!(task.github_pr_context.as_ref().unwrap().state, "unknown");

            // Swap in mock HTTP client and zero staleness threshold
            db.http = Arc::new(MockHttpClient);
            db.config = IntegrationConfig {
                github_token: Some("fake-token".into()),
                linear_api_key: None,
                staleness_threshold: Duration::from_secs(0), // always stale
            };

            // list_tasks should trigger refresh since staleness_threshold=0
            let tasks = db.list_tasks(TaskFilter::default()).unwrap();
            let refreshed = tasks.iter().find(|t| t.id == refresh_task_id).unwrap();
            let ctx = refreshed.github_pr_context.as_ref().unwrap();
            assert_eq!(ctx.state, "merged", "state should be refreshed to 'merged' from mock API response");

            // Verify it's persisted in the DB too
            let task_after = db.get_task(refresh_task_id).unwrap().unwrap();
            assert_eq!(task_after.github_pr_context.as_ref().unwrap().state, "merged");
        }

        // --- test: canceled status roundtrips ---
        {
            let canceled_id = db.add_task(make_add_task("Cancel me", "work")).unwrap();

            db.edit_task(
                canceled_id,
                EditTask {
                    status: Some(TaskStatus::Canceled),
                    ..Default::default()
                },
            )
            .unwrap();

            let task = db.get_task(canceled_id).unwrap().expect("task should exist");
            assert_eq!(task.status, TaskStatus::Canceled);

            // Canceled task should appear when filtering by canceled status
            let canceled_tasks = db.list_tasks(TaskFilter {
                status: Some(TaskStatus::Canceled),
                ..Default::default()
            }).unwrap();
            assert!(canceled_tasks.iter().any(|t| t.id == canceled_id));
            assert!(canceled_tasks.iter().all(|t| t.status == TaskStatus::Canceled));
        }
    }
}
